services:
  app-dev:
    profiles:
      - dev
    # Change the image name to match your Node.js application
    image: YOUR_NODEJS_APP:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Change the container name to match your Node.js application
    container_name: YOUR_NODEJS_APP:dev
    command: npm run dev
    # Change the port to match your Node.js application
    ports:
      - 80:80
    develop:
      watch:
        - path: .
          target: /app
          action: sync
          initial_sync: true
          ignore:
            - node_modules
