packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  config-provider/prod:
    '@clack/prompts': ^0.11.0
    tinyglobby: ^0.2.15
  core/prod:
    cac: ^6.7.14
    defu: ^6.1.4
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    '@lumirelle/stylelint-config': ^1.0.1
    '@types/node': ^24.9.2
    '@vitest/coverage-v8': ^4.0.6
    bumpp: ^10.3.1
    czg: ^1.12.0
    eslint: ^9.39.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
    stylelint: ^16.25.0
    taze: ^19.9.0
    tinyexec: ^1.0.1
    tsdown: ^0.15.12
    tsx: ^4.20.6
    typescript: ^5.9.3
    vite: ^7.1.12
    vitest: ^4.0.6
  docs:
    '@iconify-json/svg-spinners': ^1.2.4
    '@shikijs/vitepress-twoslash': ^3.14.0
    '@unocss/reset': ^66.5.4
    '@vueuse/core': ^14.0.0
    floating-vue: ^5.2.2
    pinia: ^3.0.3
    unocss: ^66.5.4
    unplugin-vue-components: ^30.0.0
    vite-tsconfig-paths: ^5.1.4
    vitepress: ^2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.5
    vue: ^3.5.22
  shared/prod:
    '@antfu/utils': ^9.3.0
    c12: ^3.3.1
    consola: ^3.4.2
    pathe: ^2.0.3
  utils/prod:
    ansis: ^4.2.0
    rc9: ^2.1.2

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

verifyDepsBeforeRun: install
