packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  config-provider/dev:
    '@types/semver': ^7.7.1
  config-provider/prod:
    '@posva/prompts': ^2.4.4
    semver: ^7.7.2
    tinyglobby: ^0.2.15
  core/prod:
    cac: ^6.7.14
    defu: ^6.1.4
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.0.1
    '@antfu/utils': ^9.2.1
    '@lumirelle/stylelint-config': ^0.0.2-beta.8
    '@types/node': ^24.5.2
    bumpp: ^10.2.3
    czg: ^1.12.0
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    stylelint: ^16.24.0
    taze: ^19.7.0
    tinyexec: ^1.0.1
    tsx: ^4.20.5
    typescript: ^5.9.2
    unbuild: ^3.6.1
    vite: ^7.1.7
    vitest: ^3.2.4
  docs:
    '@iconify-json/svg-spinners': ^1.2.4
    '@shikijs/vitepress-twoslash': ^3.13.0
    '@unocss/reset': ^66.5.2
    '@vueuse/core': ^13.9.0
    floating-vue: ^5.2.2
    pinia: ^3.0.3
    unocss: ^66.5.2
    unplugin-vue-components: ^29.1.0
    vite-tsconfig-paths: ^5.1.4
    vitepress: ^2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.3
    vue: ^3.5.21
  shared/prod:
    c12: ^3.3.0
    consola: ^3.4.2
  utils/prod:
    ansis: ^4.1.0
    rc9: ^2.1.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
