/**
 * Generated by tsnapi — public API snapshot of `starship-butler-config-provider/command/preset`
 */
// #region Classes
export declare class HandlerError extends Error {
  constructor(_: string);
}
// #endregion

// #region Functions
export declare function commandPreset(_: PresetOptions): Promise<void>;
export declare function filterActions(_: PresetOptions): Promise<Action[]>;
export declare function validateOptions(_: PresetOptions): boolean;
// #endregion

// #region Other
export { Action }
export { ActionFactory }
export { ActionHandler }
export { ActionHandlerContext }
export { ConfigPathGenerator }
export { DestinationHandler }
export { PlatformDestinationMap }
export { PresetOptions }
// #endregion