/**
 * Generated by tsnapi — public API snapshot of `starship-butler-config-provider/command/set`
 */
// #region Functions
export declare function commandSet(_: string, _: string, _: SetOptions): Promise<void>;
export declare function validateOptions(_: SetOptions): boolean;
// #endregion

// #region Other
export { SetOptions }
// #endregion