/**
 * Generated by tsnapi — public API snapshot of `starship-butler-config-provider/command/utils`
 */
// #region Other
export { copyPasteConfig }
export { processConfig }
export { ProcessConfigOptions }
export { readUserConfig }
export { symlinkConfig }
export { upsertUserConfig }
// #endregion