name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun i -g @antfu/ni
      - run: nci
      - run: nr build
      - run: nr lint
      - run: nr typecheck
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        bun: [latest]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Set bun ${{ matrix.bun }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun }}
      - run: bun i -g @antfu/ni
      - run: nci
      - run: nr build
      - run: nr test --coverage
      # If you want to get code coverage reports from Codecov
      # - uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
