name: Pkg Pr New

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: oven-sh/setup-bun@v2.0.2
      - run: bun install
      - run: bun build
      - run: bunx pkg-pr-new publish --bun
