/**
 * Generated by tsnapi — public API snapshot of `starship-butler-utils/config`
 */
// #region Types
export type ConfigLayerMeta = ConfigLayerMeta$1;
export type LoadConfigOptions<T extends UserInputConfig = UserInputConfig, MT extends ConfigLayerMeta = ConfigLayerMeta> = LoadConfigOptions$1<T, MT>;
export type RC = Record<string, any>;
export type RCOptions = typeof defaults;
// #endregion

// #region Functions
export declare function loadConfig<M extends UserInputConfig = UserInputConfig, MT extends ConfigLayerMeta = ConfigLayerMeta>(_?: LoadConfigOptions<M, MT>): Promise<ResolvedConfig<M, MT>>;
export declare function readUserConfig(_?: RCOptions): RC;
export declare function removeUserConfig(_?: RCOptions): void;
export declare function updateUserConfig(_: RC, _?: RCOptions): RC;
export declare function upsertUserConfig(_: RC, _?: RCOptions): RC | void;
export declare function writeUserConfig(_: RC, _?: RCOptions): void;
// #endregion