/**
 * Generated by tsnapi — public API snapshot of `starship-butler-utils/fs`
 */
// #region Functions
export declare function copyFile(_: string, _: string, _?: boolean): boolean;
export declare function createSymlink(_: string, _: string, _?: boolean): boolean;
export declare function ensureDirectory(_: string): boolean;
export declare function exists(_: string): boolean;
export declare function isDirectory(_: string): boolean;
export declare function isSymbolicLink(_: string): boolean;
export declare function remove(_: string, _?: boolean): boolean;
export declare function removeSymlink(_: string): boolean;
// #endregion