/**
 * Generated by tsnapi — public API snapshot of `starship-butler-utils/highlight`
 */
// #region Functions
export declare function important(_: string): string;
export declare function info(_: string): string;
export declare function success(_: string): string;
// #endregion