/**
 * Generated by tsnapi — public API snapshot of `starship-butler-utils/path`
 */
// #region Functions
export declare function appdata(..._: string[]): string;
export declare function homedir(..._: string[]): string;
export declare function localAppdata(..._: string[]): string;
// #endregion