name: Pkg Pr New

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - run: pnpm install
      - run: pnpm build
      - run: pnpm dlx pkg-pr-new publish --pnpm
