name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6.1.0
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install -g @antfu/ni
      - run: nci
      - run: nr build
      - run: nr lint
      - run: nr typecheck
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: pnpm/action-setup@v4.2.0
        with:
          run_install: false
      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - run: pnpm install -g @antfu/ni
      - run: nci
      - run: nr build
      - run: nr test --coverage
      # If you want to get code coverage reports from Codecov
      # - uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
