/**
 * Generated by tsnapi — public API snapshot of `starship-butler`
 */
// #region Interfaces
export interface ButlerConfig {
  "config-provider"?: ConfigProviderOptions;
}
// #endregion

// #region Types
export type SafeButlerConfig = Omit<ButlerConfig, "config-provider"> & {
  "config-provider"?: Omit<ConfigProviderOptions, "version">;
};
// #endregion

// #region Functions
export declare function defineButlerConfig(_: SafeButlerConfig): SafeButlerConfig;
export declare function loadConfig(_?: RCOptions & LoadConfigOptions<ButlerConfig>): Promise<ButlerConfig>;
// #endregion

// #region Re-exports
export * from "starship-butler-types";
// #endregion