/**
 * Generated by tsnapi — public API snapshot of `starship-butler-config-provider/constants`
 */
// #region Variables
export declare const ASSETS_FOLDER: string;
export declare const PKG_ROOT: string;
// #endregion