/**
 * Generated by tsnapi — public API snapshot of `starship-butler-config-provider`
 */
// #region Interfaces
export interface ConfigProviderOptions {
  preset?: PresetOptions & {
    rime?: {
      ctrlSpaceDisabled?: boolean;
    };
  };
  set?: SetOptions;
  version?: string;
}
// #endregion