name: Release Commit

on: [push, pull_request]

permissions: {}

jobs:
  release-commit:
    uses: lumirelle/workflows/.github/workflows/release.yml@v4
    permissions:
      contents: write
      id-token: write
    with:
      changelog: false
      publish: true
      build: node -v
